Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,10 +7,14 @@ on:
 env:
   AWS_REGION: us-east-2
   ECR_REPOSITORY: 671336841184.dkr.ecr.us-east-2.amazonaws.com/ecr-iisc-aimlops-cap-fe-streamlite
-  ECS_CLUSTER: ecs-cluster-iisc-aimlops-cap-fe-streamlite
-  ECS_SERVICE: ecs-cluster-iisc-aimlops-cap-fe-streamlite-service
-  TASK_DEF_FAMILY: ecs-cluster-iisc-aimlops-cap-fe-streamlite-task
-  CONTAINER_NAME: ecs-cluster-iisc-aimlops-cap-fe-streamlite-container
+  ECS_CLUSTER: ecs-iisc-aimlops-cap
+  ECS_SERVICE: ecs-svc-iisc-aimlops-cap-fe
+  TASK_DEF_FAMILY: ecs-iisc-aimlops-cap-task-fe
+  CONTAINER_NAME: ecs-iisc-aimlops-cap-container-fe
+  TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:us-east-2:671336841184:targetgroup/tg-iisc-aimlops-cap-fe/28f758deaac37d0e
+  SUBNET1: "subnet-02a7a02a9f8feff33"
+  SUBNET2: "subnet-06ad8298d28daac66"
+  SG_ID: "sg-0aa4d6e1ecdf15128"
 
 jobs:
   deploy:
@@ -67,10 +71,30 @@ jobs:
           --output text)
         echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
 
-    - name: Deploy New Task Definition to ECS
+    - name: Create or Update ECS Service
       run: |
-        aws ecs update-service \
+        SERVICE_EXISTS=$(aws ecs describe-services \
           --cluster $ECS_CLUSTER \
-          --service $ECS_SERVICE \
-          --task-definition $TASK_DEF_ARN \
-          --force-new-deployment
+          --services $ECS_SERVICE \
+          --query "services[0].status" \
+          --output text || echo "MISSING")
+
+        if [ "$SERVICE_EXISTS" = "ACTIVE" ]; then
+          echo "Service exists. Updating..."
+          aws ecs update-service \
+            --cluster $ECS_CLUSTER \
+            --service $ECS_SERVICE \
+            --task-definition $TASK_DEF_ARN \
+            --force-new-deployment
+        else
+          echo "Service does not exist. Creating..."
+          aws ecs create-service \
+            --cluster $ECS_CLUSTER \
+            --service-name $ECS_SERVICE \
+            --task-definition $TASK_DEF_ARN \
+            --launch-type FARGATE \
+            --desired-count 1 \
+            --network-configuration "awsvpcConfiguration={subnets=[\"$SUBNET1\",\"$SUBNET2\"],securityGroups=[\"$SG_ID\"],assignPublicIp=\"ENABLED\"}" \
+            --load-balancers "targetGroupArn=$TARGET_GROUP_ARN,containerName=$CONTAINER_NAME,containerPort=8000" \
+            --platform-version LATEST
+        fi
